### ISSUE TITLE
About exportName

### ISSUE THREAD

**Issue by poppinlp** [el2iot2/grunt-hogan#33]
I wanna use some export name like `_aaa.bbb.ccc`, but this won't work now.
Because `exportName = this.target` and target named `_aaa.bbb.ccc` won't run in grunt task.
Maybe there's a good way to resolve this problem: add a option called `namespace` and use this as `exportName`.

If you think it's OK, i'm glad to send PR to do this.

**Comment by automatonic** [comment]
Sorry...Just now noticed your reply. I would definitely consider a PR, assuming that the existing method continues to work "as is".

I would expect that the presence of such a `namespace` variable would override the default `target` based behavior.

Thanks!
